sudo: required

dist: trusty
language: node_js
node_js:
  - "node"

cache: yarn

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

install:
  - npm install

before_install:
  # needed for Travis.ci (https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-directly)
  - export CHROME_BIN=/usr/bin/google-chrome
  # gui is needed to run tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  # from http://gist.asciidoctor.org/?github-mraible%2Fng2-demo%2F%2FREADME.adoc#_travis_ci
  - ng test --watch false
  - ng e2e

matrix:
  fast_finish: true
